
// ============= DEFINE NUMBERS ================

// PROPERTIES -------------

#define PROPERTY_CLUSTERDEVIATION_METERS 25
#define PROPERTY_CLUSTERSPEED -25

#define PROPERTY_EXPLOSIVEAMOUNT 5

#define PROPERTY_EXPLOSIVESPEED_X 0
#define PROPERTY_EXPLOSIVESPEED_Y 10
#define PROPERTY_EXPLOSIVESPEED_Z -20

// MATERIALS -------------

#define MATERIALS_COST_LARGEEXPLOSIVE 500
#define MATERIALS_COST_BIGEXPLOSIVE 400
#define MATERIALS_COST_MEDIUMEXPLOSIVE 300
#define MATERIALS_COST_SMALLEXPLOSIVE 250

#define MATERIALS_DEFAULT_EXPLOSIVES 3000
#define MATERIALS_DEFAULT_CLUSTERS 200

#define MATERIALS_MIN_CLUSTERS 5
#define MATERIALS_MAX_CLUSTERS 100

#define MATERIALS_MIN_FUSETIMER 2
#define MATERIALS_MAX_FUSETIMER 10

// CONTAINER -------------

#define CONTAINER_ACECARGO_MULTIPLIER 3

// INTERACTIONS -------------

#define DISTANCE_USE_MIN 5

#define DISTANCE_INITIALCARRY_BARREL_X 0
#define DISTANCE_INITIALCARRY_BARREL_Y 1.3
#define DISTANCE_INITIALCARRY_BARREL_Z 0.5

#define DISTANCE_MIN_CREATEBARREL_X 0
#define DISTANCE_MIN_CREATEBARREL_Y 1
#define DISTANCE_MIN_CREATEBARREL_Z 0

#define DISTANCE_DEVIATION_CREATEBARREL_X 2

#define DISTANCE_CREATEBARREL_LOWER_Z 2.5

// VOLUME -------------

#define VOLUME_BOMBMAKING_DISTANCE_METERS 20
#define VOLUME_FALLINGSOUND_DISTANCE_METERS 600

#define VOLUME_BOMBMAKING 10
#define VOLUME_FALLINGSOUND 60

// DURATION -------------

#define DURATION_BOMBMAKING_SECONDS 12
#define DURATION_LOADINGBARREL_SECONDS 3.5

#define DURATION_BARREL_ACTIVATION_MIN 0.5

// INTERVALS -------------

#define INTERVAL_FALLINGSOUND_START_SECONDS 2
#define INTERVAL_CLUSTEREXPLOSION_SECONDS 0.5

// DIALOG IDC -------------

// BOMB PREP ==============

#define DIALOG_BOMBPREP_IDC 1001 

#define TEXT_PAYLOAD_IDC 101
#define TEXT_FUSETIMER_IDC 102
#define TEXT_CLUSTER_IDC 103

#define SUBTXT_FUSETIMER_IDC 200
#define SUBTXT_CLUSTERAMNT_IDC 201

#define	COMBO_FUSE_IDC 300
#define COMBO_PAYLOAD_IDC 301

#define SLIDER_FUSETIMER_IDC 400
#define SLIDER_CLUSTERAMNT_IDC 401

#define SLIDER_FUSETIMER_INITIAL 5
#define SLIDER_CLUSTERAMNT_INITIAL 30

#define PROGREESS_EXPLOSIVESLEFT_IDC 500
#define PROGREESS_CLUSTERSLEFT_IDC 501

#define BUTTON_CONFIRM_MAKEBARREL 999

// BOMB DROP ==============

#define DIALOG_BOMBDROP_IDC 1002

#define LIST_LOADEDBARRELS_IDC 300
#define PROGRESS_CARGOLOAD_IDC 302
